# Who is allowed to use the bot?
allowlist:
  - "@user:example.com"
# The prefix for the main command without the !
command_prefix: spotify

#spotify_client_id: REQUIRED
#spotify_client_secret: REQUIRED
